name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  sis
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Build
        # Those are the commands which are ran on the GitHub Virtual Machine.
        # `test` task disabled because using SpringBootTest.
        run: |
          chmod +x gradlew
          ./gradlew build -x test --info